name: Création des repository avec terraform

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ master ]

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    name: Terraform
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false #This flag means there won't be a wrapper that highjacks the STDOUT from the Terraform commands.

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./repository # Use your environment folder
      shell: bash

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan
      working-directory: ./repository # Use your environment folder
      shell: bash

    - name: Terraform Show
      id: show
      run: terraform show -no-color tf.plan 2>&1 > /tmp/plan.txt
      working-directory: ./repository # Use your environment folder
      shell: bash

    - uses: trstringer/manual-approval@v1
      timeout-minutes: 15
      with:
        secret: ${{ secrets.TOKEN }}
        approvers: mcampagna
        minimum-approvals: 1
        issue-title: "Deploy github repository with terraform"

    - name: Terraform Apply
      run: terraform apply -input=false tf.plan
      working-directory: ./repository # Use your environment folder
      shell: bash
